server:
  port: 8002

spring:
  application:
    name: ticket-show
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  
  # Nacos 配置导入
  config:
    import: optional:nacos:ticket-show.yaml
  
  # Nacos 服务发现配置
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        enabled: true
        namespace: ""
        group: DEFAULT_GROUP
        register-enabled: true
        ip: 127.0.0.1
        prefer-ip-address: false
      config:
        enabled: true
        import-check:
          enabled: false
  
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:ticket_show_db}?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
    hikari:
      maximum-pool-size: ${DB_MAX_POOL_SIZE:50}
      minimum-idle: ${DB_MIN_IDLE:10}
      connection-timeout: ${DB_CONNECTION_TIMEOUT:60000}
      idle-timeout: ${DB_IDLE_TIMEOUT:600000}
      max-lifetime: ${DB_MAX_LIFETIME:1800000}
      leak-detection-threshold: ${DB_LEAK_DETECTION_THRESHOLD:60000}
      validation-timeout: ${DB_VALIDATION_TIMEOUT:5000}
      initialization-fail-timeout: ${DB_INIT_FAIL_TIMEOUT:1}

  # Redis配置
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    database: ${REDIS_DATABASE:0}
    timeout: ${REDIS_TIMEOUT:5000}
    # password: ${REDIS_PASSWORD:}  # 注释掉密码配置，避免无密码时的AUTH错误

  # Elasticsearch配置
  data:
    elasticsearch:
      repositories:
        enabled: true
      client:
        reactive:
          endpoints: ${ES_ENDPOINTS:localhost:9200}
  
  # 定时任务配置
  task:
    scheduling:
      enabled: true
      pool:
        size: 5
      thread-name-prefix: show-task-
    execution:
      pool:
        core-size: 10
        max-size: 20
        queue-capacity: 100
        keep-alive: 60s

# MyBatis-Plus配置
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.ticketsystem.show.entity
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0

# Knife4j配置
knife4j:
  enable: true
  openapi:
    title: 演出服务API文档
    description: 演出服务相关接口
    email: admin@ticketsystem.com
    version: 1.0
    group:
      show:
        group-name: 演出服务
        api-rule: package
        api-rule-resources:
          - com.ticketsystem.show.controller

# Spring Boot Actuator配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,stock-monitor
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    web:
      server:
        request:
          autotime:
            enabled: true
    tags:
      application: ${spring.application.name}
      environment: ${spring.profiles.active}



# 日志配置
logging:
  level:
    com.ticketsystem.show: ${LOG_LEVEL:debug}
    org.springframework.data.elasticsearch: ${LOG_LEVEL:info}
    org.springframework.scheduling: ${LOG_LEVEL:info}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
  file:
    name: logs/ticket-show.log
    max-size: ${LOG_MAX_SIZE:100MB}
    max-history: ${LOG_MAX_HISTORY:30}